//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BzReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BzReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting.
        /// </summary>
        internal static string AbortingIndexing {
            get {
                return ResourceManager.GetString("AbortingIndexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutProduct {
            get {
                return ResourceManager.GetString("AboutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BzReader.
        /// </summary>
        internal static string BzReader {
            get {
                return ResourceManager.GetString("BzReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Wiki topic title carryover occurred, but no previous block has been stored.
        /// </summary>
        internal static string CarryoverNoPrevBlock {
            get {
                return ResourceManager.GetString("CarryoverNoPrevBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseIndexingForm {
            get {
                return ResourceManager.GetString("CloseIndexingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump file {0} does not exist.
        /// </summary>
        internal static string DumpFileDoesNotExist {
            get {
                return ResourceManager.GetString("DumpFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA: {0}.
        /// </summary>
        internal static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed finishing the search work item due to timeout.
        /// </summary>
        internal static string FailedFinishingSearch {
            get {
                return ResourceManager.GetString("FailedFinishingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading {0} block starting at {1}: {2}.
        /// </summary>
        internal static string FailedLoadingBlock {
            get {
                return ResourceManager.GetString("FailedLoadingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed locating the blocks in {0}: {1}.
        /// </summary>
        internal static string FailedLocatingBlocks {
            get {
                return ResourceManager.GetString("FailedLocatingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed starting the search work item due to timeout.
        /// </summary>
        internal static string FailedStartingSearch {
            get {
                return ResourceManager.GetString("FailedStartingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed uncompressing block starting at {0}: too much memory required.
        /// </summary>
        internal static string FailedUncompressingMemory {
            get {
                return ResourceManager.GetString("FailedUncompressingMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed uncompressing block starting at {0}: {1}.
        /// </summary>
        internal static string FailedUncompressingStatus {
            get {
                return ResourceManager.GetString("FailedUncompressingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~ {0} hours and {1} minutes.
        /// </summary>
        internal static string FinishingInHours {
            get {
                return ResourceManager.GetString("FinishingInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a jiffy!.
        /// </summary>
        internal static string FinishingSoon {
            get {
                return ResourceManager.GetString("FinishingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flushing documents to disk.
        /// </summary>
        internal static string FlushingDocumentsToDisk {
            get {
                return ResourceManager.GetString("FlushingDocumentsToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b style=&quot;color: #FF0000;&quot;&gt;FORMATTER ERROR (Malformed List)&lt;/b&gt;.
        /// </summary>
        internal static string FormatterErrorMalformedList {
            get {
                return ResourceManager.GetString("FormatterErrorMalformedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;FORMATTER ERROR (Malformed Table)&lt;/b&gt;.
        /// </summary>
        internal static string FormatterErrorMalformedTable {
            get {
                return ResourceManager.GetString("FormatterErrorMalformedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of HTTP request string parts.
        /// </summary>
        internal static string HTTPRequestNoStringParts {
            get {
                return ResourceManager.GetString("HTTPRequestNoStringParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too few strings in the HTTP request.
        /// </summary>
        internal static string HTTPRequestTooFewStrings {
            get {
                return ResourceManager.GetString("HTTPRequestTooFewStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index does not exist for {0}.
        /// </summary>
        internal static string IndexDoesNotExist {
            get {
                return ResourceManager.GetString("IndexDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string IndexingDoneETA {
            get {
                return ResourceManager.GetString("IndexingDoneETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bz2 blocks were found in {0}.
        /// </summary>
        internal static string NoBlocksFound {
            get {
                return ResourceManager.GetString("NoBlocksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate text end for topic {0} in block.
        /// </summary>
        internal static string NoTextEndInBlock {
            get {
                return ResourceManager.GetString("NoTextEndInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate text marker for topic {0} in block.
        /// </summary>
        internal static string NoTextMarkerInBlock {
            get {
                return ResourceManager.GetString("NoTextMarkerInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate text start for topic {0} in block.
        /// </summary>
        internal static string NoTextStartInBlock {
            get {
                return ResourceManager.GetString("NoTextStartInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate topic {0} in block.
        /// </summary>
        internal static string NoTopicInBlock {
            get {
                return ResourceManager.GetString("NoTopicInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No topics were found in the block.
        /// </summary>
        internal static string NoTopicsInBlock {
            get {
                return ResourceManager.GetString("NoTopicsInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia dump files (*.xml.bz2)|*.xml.bz2|All files (*.*)|*.*.
        /// </summary>
        internal static string OpenDumpFilter {
            get {
                return ResourceManager.GetString("OpenDumpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing index.
        /// </summary>
        internal static string OptimizingIndex {
            get {
                return ResourceManager.GetString("OptimizingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BzReader is a Wikipedia compressed dump browser.
        /// </summary>
        internal static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is licensed under GPLv2.
        /// </summary>
        internal static string ProductLicense {
            get {
                return ResourceManager.GetString("ProductLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing.
        /// </summary>
        internal static string ProgressIndexing {
            get {
                return ResourceManager.GetString("ProgressIndexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating the blocks.
        /// </summary>
        internal static string ProgressLocatingBlocks {
            get {
                return ResourceManager.GetString("ProgressLocatingBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for &apos;{0}&apos;.
        /// </summary>
        internal static string SearchingForTerm {
            get {
                return ResourceManager.GetString("SearchingForTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} top results.
        /// </summary>
        internal static string ShowingXTopResults {
            get {
                return ResourceManager.GetString("ShowingXTopResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown HTTP request type {0}.
        /// </summary>
        internal static string UnknownHTTPRequestType {
            get {
                return ResourceManager.GetString("UnknownHTTPRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF8 decoder could not complete the conversion.
        /// </summary>
        internal static string UTFDecoderError {
            get {
                return ResourceManager.GetString("UTFDecoderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for {0} tokenizer threads to finish.
        /// </summary>
        internal static string WaitingForTokenizers {
            get {
                return ResourceManager.GetString("WaitingForTokenizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BzReader - {0}.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
